package com.example.jxsms.ui.emailbackup

import android.content.ActivityNotFoundException
import android.content.Intent
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.heightIn
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.Checkbox
import androidx.compose.material3.DatePickerDialog
import androidx.compose.material3.DateRangePicker
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.FilterChip
import androidx.compose.material3.LinearProgressIndicator
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.TopAppBar
import androidx.compose.material3.rememberDateRangePickerState
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.annotation.StringRes
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.example.jxsms.R
import com.example.jxsms.data.backup.EmailBackupBatchEntity
import com.example.jxsms.data.backup.EmailBackupPartEntity
import com.example.jxsms.domain.backup.EmailBackupBatchStatus
import com.example.jxsms.domain.backup.EmailBackupPartStatus
import com.example.jxsms.domain.backup.EmailBackupRange
import com.example.jxsms.domain.model.SmsCategory
import kotlinx.coroutines.launch
import java.text.DateFormat
import java.time.Instant
import java.time.LocalDate
import java.time.ZoneId
import java.time.ZoneOffset
import java.util.Date

private enum class BackupPage { EDITOR, PREVIEW, QUEUE }

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun EmailBackupScreen(
    vm: EmailBackupViewModel,
    onBack: () -> Unit,
    onHistory: () -> Unit
) {
    val options by vm.options.collectAsStateWithLifecycle()
    val preview by vm.preview.collectAsStateWithLifecycle()
    val progress by vm.progress.collectAsStateWithLifecycle()
    val error by vm.error.collectAsStateWithLifecycle()
    val generated by vm.generated.collectAsStateWithLifecycle()
    val awaitingPart by vm.awaitingPart.collectAsStateWithLifecycle()
    val duplicate by vm.duplicate.collectAsStateWithLifecycle()
    var page by rememberSaveable { mutableStateOf(BackupPage.EDITOR) }
    var showDates by remember { mutableStateOf(false) }
    var showOriginalWarning by remember { mutableStateOf(false) }
    val context = LocalContext.current
    val scope = rememberCoroutineScope()
    var launchError by remember { mutableStateOf<String?>(null) }
    val launcher = rememberLauncherForActivityResult(ActivityResultContracts.StartActivityForResult()) {
        // Returning from Gmail is not proof that the message was sent.
    }

    fun openPart(part: EmailBackupPartEntity) {
        scope.launch {
            try {
                val email = vm.createIntent(part.partId)
                launcher.launch(email.intent)
                vm.markOpened(part.partId)
            } catch (_: ActivityNotFoundException) {
                launchError = "no_email_app"
            } catch (error: Exception) {
                launchError = error.message ?: "open_email_failed"
            }
        }
    }

    LaunchedEffect(preview) {
        if (preview != null && page == BackupPage.EDITOR) page = BackupPage.PREVIEW
    }
    LaunchedEffect(generated?.backupId) {
        val backup = generated ?: return@LaunchedEffect
        page = BackupPage.QUEUE
        val first = backup.parts.firstOrNull() ?: return@LaunchedEffect
        try {
            val email = vm.createIntent(first.partId)
            launcher.launch(email.intent)
            vm.markOpened(first.partId)
        } catch (_: ActivityNotFoundException) {
            launchError = "no_email_app"
        } catch (error: Exception) {
            launchError = error.message ?: "open_email_failed"
        }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text(stringResource(R.string.email_backup_title)) },
                navigationIcon = {
                    TextButton(onClick = {
                        when (page) {
                            BackupPage.EDITOR -> onBack()
                            BackupPage.PREVIEW -> page = BackupPage.EDITOR
                            BackupPage.QUEUE -> onBack()
                        }
                    }) { Text(stringResource(R.string.back)) }
                },
                actions = {
                    TextButton(onClick = onHistory) {
                        Text(stringResource(R.string.backup_history))
                    }
                }
            )
        }
    ) { padding ->
        when (page) {
            BackupPage.EDITOR -> BackupEditor(
                modifier = Modifier.padding(padding),
                options = options,
                preview = preview,
                onRecipient = vm::updateRecipient,
                onRange = vm::updateRange,
                onCustomRange = { showDates = true },
                onCategory = vm::toggleCategory,
                onOtpRedaction = {
                    vm.updateRedaction { copy(redactOtp = it) }
                },
                onLongRedaction = {
                    vm.updateRedaction { copy(redactLongNumbers = it) }
                },
                onOriginal = {
                    if (it) showOriginalWarning = true
                    else vm.updateRedaction { copy(includeOriginalBodyInJson = false) }
                },
                onPreview = vm::preview
            )
            BackupPage.PREVIEW -> preview?.let {
                BackupPreview(
                    modifier = Modifier.padding(padding),
                    preview = it,
                    onEdit = { page = BackupPage.EDITOR },
                    onGenerate = vm::requestGenerate
                )
            }
            BackupPage.QUEUE -> BackupQueue(
                modifier = Modifier.padding(padding),
                generatedParts = generated?.parts.orEmpty(),
                awaitingPart = awaitingPart,
                onOpen = { partId ->
                    scope.launch {
                        val part = generated?.parts?.firstOrNull { it.partId == partId }
                        if (part != null) {
                            try {
                                val email = vm.createIntent(part.partId)
                                launcher.launch(email.intent)
                                vm.markOpened(part.partId)
                            } catch (_: ActivityNotFoundException) {
                                launchError = "no_email_app"
                            } catch (error: Exception) {
                                launchError = error.message ?: "open_email_failed"
                            }
                        }
                    }
                },
                onHistory = onHistory
            )
        }
        if (progress != null) {
            ProgressDialog(progress!!, vm::cancelWork)
        }
    }

    if (showDates) {
        BackupDateRangeDialog(
            onDismiss = { showDates = false },
            onSelect = { start, end ->
                vm.updateCustomRange(start, end)
                showDates = false
            }
        )
    }
    if (showOriginalWarning) {
        AlertDialog(
            onDismissRequest = { showOriginalWarning = false },
            title = { Text(stringResource(R.string.original_json_warning_title)) },
            text = { Text(stringResource(R.string.original_json_warning_body)) },
            confirmButton = {
                TextButton(onClick = {
                    vm.updateRedaction { copy(includeOriginalBodyInJson = true) }
                    showOriginalWarning = false
                }) { Text(stringResource(R.string.confirm)) }
            },
            dismissButton = {
                TextButton(onClick = { showOriginalWarning = false }) {
                    Text(stringResource(R.string.cancel))
                }
            }
        )
    }
    if (duplicate != null) {
        AlertDialog(
            onDismissRequest = vm::clearDuplicate,
            title = { Text(stringResource(R.string.duplicate_backup_title)) },
            text = {
                Text(stringResource(
                    if (duplicate!!.confirmed) R.string.duplicate_backup_confirmed
                    else R.string.duplicate_backup_unfinished
                ))
            },
            confirmButton = {
                TextButton(onClick = vm::generateAnyway) {
                    Text(stringResource(R.string.generate_again))
                }
            },
            dismissButton = {
                TextButton(onClick = {
                    if (duplicate!!.confirmed) vm.clearDuplicate() else vm.continueDuplicate()
                }) {
                    Text(stringResource(
                        if (duplicate!!.confirmed) R.string.cancel
                        else R.string.continue_existing_backup
                    ))
                }
            }
        )
    }
    val visibleError = error ?: launchError
    if (visibleError != null) {
        AlertDialog(
            onDismissRequest = {
                vm.clearError()
                launchError = null
            },
            title = { Text(stringResource(R.string.backup_error_title)) },
            text = { Text(backupErrorText(visibleError)) },
            confirmButton = {
                TextButton(onClick = {
                    vm.clearError()
                    launchError = null
                }) { Text(stringResource(R.string.confirm)) }
            }
        )
    }
    if (awaitingPart != null) {
        SendConfirmationDialog(
            part = awaitingPart!!,
            onSent = {
                vm.confirmPartSent(awaitingPart!!.partId) { next ->
                    if (next != null) openPart(next)
                }
            },
            onNotSent = { vm.reportPartNotSent(awaitingPart!!.partId) },
            onReopen = { openPart(awaitingPart!!) },
            onEnd = { vm.setAwaitingPart(null) }
        )
    }
}

@Composable
private fun BackupEditor(
    modifier: Modifier,
    options: com.example.jxsms.domain.backup.EmailBackupOptions,
    preview: com.example.jxsms.domain.backup.EmailBackupPreview?,
    onRecipient: (String) -> Unit,
    onRange: (EmailBackupRange) -> Unit,
    onCustomRange: () -> Unit,
    onCategory: (SmsCategory) -> Unit,
    onOtpRedaction: (Boolean) -> Unit,
    onLongRedaction: (Boolean) -> Unit,
    onOriginal: (Boolean) -> Unit,
    onPreview: () -> Unit
) {
    LazyColumn(modifier.fillMaxSize().padding(horizontal = 16.dp)) {
        item {
            Text(stringResource(R.string.recipient), fontWeight = FontWeight.Bold)
            OutlinedTextField(
                value = options.recipient,
                onValueChange = onRecipient,
                modifier = Modifier.fillMaxWidth(),
                singleLine = true,
                placeholder = { Text("user@example.com") }
            )
            SectionTitle(stringResource(R.string.backup_range))
            Row(
                Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(6.dp)
            ) {
                RangeChip(EmailBackupRange.UNBACKED, options.range, onRange)
                RangeChip(EmailBackupRange.LAST_7_DAYS, options.range, onRange)
                RangeChip(EmailBackupRange.LAST_30_DAYS, options.range, onRange)
            }
            Row(
                Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(6.dp)
            ) {
                RangeChip(EmailBackupRange.THIS_MONTH, options.range, onRange)
                FilterChip(
                    selected = options.range == EmailBackupRange.CUSTOM,
                    onClick = onCustomRange,
                    label = { Text(stringResource(R.string.range_custom)) }
                )
            }
            SectionTitle(stringResource(R.string.include_categories))
            SmsCategory.entries.forEach { category ->
                CheckLine(
                    stringResource(categoryStringRes(category)),
                    category in options.includedCategories,
                    { onCategory(category) }
                )
            }
            SectionTitle(stringResource(R.string.privacy_protection))
            SwitchLine(
                stringResource(R.string.redact_otp),
                options.redaction.redactOtp,
                onOtpRedaction
            )
            SwitchLine(
                stringResource(R.string.redact_long_numbers),
                options.redaction.redactLongNumbers,
                onLongRedaction
            )
            SwitchLine(
                stringResource(R.string.include_original_json),
                options.redaction.includeOriginalBodyInJson,
                onOriginal
            )
            preview?.let {
                Text(stringResource(R.string.estimated_messages, it.messages.size))
                Text(stringResource(R.string.estimated_emails, it.parts.size))
                Text(stringResource(
                    R.string.estimated_attachment,
                    it.estimatedAttachmentBytes / 1024
                ))
            }
            Spacer(Modifier.height(12.dp))
            Button(
                onClick = onPreview,
                enabled = options.recipient.isNotBlank() &&
                    options.includedCategories.isNotEmpty(),
                modifier = Modifier.fillMaxWidth()
            ) { Text(stringResource(R.string.preview)) }
            Spacer(Modifier.height(24.dp))
        }
    }
}

@Composable
private fun BackupPreview(
    modifier: Modifier,
    preview: com.example.jxsms.domain.backup.EmailBackupPreview,
    onEdit: () -> Unit,
    onGenerate: () -> Unit
) {
    LazyColumn(modifier.fillMaxSize().padding(horizontal = 16.dp)) {
        item {
            SectionTitle(stringResource(R.string.preview))
            InfoLine(stringResource(R.string.recipient), preview.options.recipient)
            InfoLine(
                stringResource(R.string.backup_range),
                formatRange(preview.resolvedRange.startInclusive, preview.resolvedRange.endInclusive)
            )
            InfoLine(stringResource(R.string.messages), preview.messages.size.toString())
            preview.categoryCounts.forEach { (category, count) ->
                InfoLine(stringResource(categoryStringRes(category)), count.toString())
            }
            InfoLine(stringResource(R.string.estimated_emails_label), preview.parts.size.toString())
            InfoLine(
                stringResource(R.string.estimated_attachment_label),
                "${preview.estimatedAttachmentBytes / 1024} KB"
            )
            InfoLine(
                stringResource(R.string.original_body_in_json),
                stringResource(
                    if (preview.options.redaction.includeOriginalBodyInJson) R.string.yes
                    else R.string.no
                )
            )
            SectionTitle(stringResource(R.string.first_subject))
            Text(preview.firstSubject)
            SectionTitle(stringResource(R.string.first_ten_messages))
        }
        items(preview.messages.take(10), key = { it.fingerprint }) { message ->
            Column(Modifier.padding(vertical = 8.dp)) {
                Text(
                    "${message.sms.contactName ?: message.sms.address} · " +
                        stringResource(categoryStringRes(message.sms.category)),
                    fontWeight = FontWeight.SemiBold
                )
                Text(message.redactedBody, maxLines = 5, overflow = TextOverflow.Ellipsis)
            }
        }
        item {
            Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                TextButton(onClick = onEdit, modifier = Modifier.weight(1f)) {
                    Text(stringResource(R.string.back_to_edit))
                }
                Button(onClick = onGenerate, modifier = Modifier.weight(1f)) {
                    Text(stringResource(R.string.generate_open_gmail))
                }
            }
            Spacer(Modifier.height(24.dp))
        }
    }
}

@Composable
private fun BackupQueue(
    modifier: Modifier,
    generatedParts: List<com.example.jxsms.domain.backup.GeneratedBackupPart>,
    awaitingPart: EmailBackupPartEntity?,
    onOpen: (String) -> Unit,
    onHistory: () -> Unit
) {
    Column(
        modifier.fillMaxSize().padding(20.dp),
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        Text(
            stringResource(R.string.backup_generated, generatedParts.size),
            style = MaterialTheme.typography.titleLarge
        )
        Spacer(Modifier.height(12.dp))
        generatedParts.forEach { part ->
            TextButton(onClick = { onOpen(part.partId) }) {
                Text(stringResource(
                    R.string.open_email_part,
                    part.partNumber,
                    part.partCount
                ))
            }
        }
        if (awaitingPart != null) {
            Text(stringResource(R.string.waiting_for_confirmation, awaitingPart.partNumber))
        }
        Spacer(Modifier.height(12.dp))
        TextButton(onClick = onHistory) { Text(stringResource(R.string.backup_history)) }
    }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
private fun BackupDateRangeDialog(
    onDismiss: () -> Unit,
    onSelect: (LocalDate, LocalDate) -> Unit
) {
    val state = rememberDateRangePickerState()
    DatePickerDialog(
        onDismissRequest = onDismiss,
        confirmButton = {
            TextButton(
                onClick = {
                    val start = state.selectedStartDateMillis
                    val end = state.selectedEndDateMillis
                    if (start != null && end != null) {
                        onSelect(
                            Instant.ofEpochMilli(start).atZone(ZoneOffset.UTC).toLocalDate(),
                            Instant.ofEpochMilli(end).atZone(ZoneOffset.UTC).toLocalDate()
                        )
                    }
                },
                enabled = state.selectedStartDateMillis != null &&
                    state.selectedEndDateMillis != null
            ) { Text(stringResource(R.string.confirm)) }
        },
        dismissButton = {
            TextButton(onClick = onDismiss) { Text(stringResource(R.string.cancel)) }
        }
    ) {
        DateRangePicker(
            state = state,
            modifier = Modifier.heightIn(max = 560.dp),
            title = { Text(stringResource(R.string.choose_date_range), Modifier.padding(16.dp)) }
        )
    }
}

@Composable
private fun ProgressDialog(progress: BackupProgress, onCancel: () -> Unit) {
    AlertDialog(
        onDismissRequest = {},
        title = {
            Text(stringResource(
                if (progress.stage == BackupProgress.Stage.PREPARING) {
                    R.string.preparing_messages
                } else {
                    R.string.generating_emails
                }
            ))
        },
        text = {
            Column {
                LinearProgressIndicator(
                    progress = {
                        if (progress.total <= 0) 0f
                        else progress.current.toFloat() / progress.total
                    },
                    modifier = Modifier.fillMaxWidth()
                )
                Text("${progress.current} / ${progress.total}")
            }
        },
        confirmButton = {
            TextButton(onClick = onCancel) { Text(stringResource(R.string.cancel)) }
        }
    )
}

@Composable
private fun SendConfirmationDialog(
    part: EmailBackupPartEntity,
    onSent: () -> Unit,
    onNotSent: () -> Unit,
    onReopen: () -> Unit,
    onEnd: () -> Unit
) {
    AlertDialog(
        onDismissRequest = onEnd,
        title = { Text(stringResource(R.string.was_email_sent, part.partNumber)) },
        text = { Text(stringResource(R.string.gmail_return_explanation)) },
        confirmButton = {
            TextButton(onClick = onSent) { Text(stringResource(R.string.sent_continue)) }
        },
        dismissButton = {
            Column(horizontalAlignment = Alignment.End) {
                TextButton(onClick = onNotSent) {
                    Text(stringResource(R.string.not_sent))
                }
                TextButton(onClick = onReopen) {
                    Text(stringResource(R.string.reopen_email))
                }
                TextButton(onClick = onEnd) { Text(stringResource(R.string.end_flow)) }
            }
        }
    )
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun EmailBackupHistoryScreen(
    vm: EmailBackupViewModel,
    onBack: () -> Unit,
    onRegenerate: () -> Unit
) {
    val batches by vm.batches.collectAsStateWithLifecycle()
    val parts by vm.selectedHistoryParts.collectAsStateWithLifecycle()
    val awaitingPart by vm.awaitingPart.collectAsStateWithLifecycle()
    var selectedBatch by remember { mutableStateOf<EmailBackupBatchEntity?>(null) }
    var deleteBatch by remember { mutableStateOf<EmailBackupBatchEntity?>(null) }
    var confirmSent by remember { mutableStateOf<EmailBackupBatchEntity?>(null) }
    val scope = rememberCoroutineScope()
    val launcher = rememberLauncherForActivityResult(ActivityResultContracts.StartActivityForResult()) {}
    var error by remember { mutableStateOf<String?>(null) }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text(stringResource(R.string.backup_history)) },
                navigationIcon = {
                    TextButton(onClick = onBack) { Text(stringResource(R.string.back)) }
                }
            )
        }
    ) { padding ->
        if (batches.isEmpty()) {
            Box(Modifier.padding(padding).fillMaxSize(), contentAlignment = Alignment.Center) {
                Text(stringResource(R.string.no_backup_history))
            }
        } else {
            LazyColumn(Modifier.padding(padding).padding(horizontal = 12.dp)) {
                items(batches, key = { it.backupId }) { batch ->
                    Column(Modifier.fillMaxWidth().padding(vertical = 10.dp)) {
                        Text(
                            DateFormat.getDateTimeInstance().format(Date(batch.createdAt)),
                            fontWeight = FontWeight.Bold
                        )
                        Text(batch.recipient)
                        Text(formatRange(batch.rangeStart, batch.rangeEnd))
                        Text(stringResource(
                            R.string.history_message_parts,
                            batch.totalMessageCount,
                            batch.partCount
                        ))
                        Text(backupStatusText(batch.status))
                        Row {
                            TextButton(onClick = {
                                selectedBatch = batch
                                vm.loadHistoryParts(batch.backupId)
                            }) { Text(stringResource(R.string.details)) }
                            TextButton(onClick = { confirmSent = batch }) {
                                Text(stringResource(R.string.mark_sent))
                            }
                            TextButton(onClick = {
                                vm.regenerate(batch, onRegenerate)
                            }) { Text(stringResource(R.string.regenerate)) }
                        }
                        Row {
                            TextButton(onClick = { vm.markBatchNotSent(batch.backupId) }) {
                                Text(stringResource(R.string.mark_not_sent))
                            }
                            TextButton(onClick = { deleteBatch = batch }) {
                                Text(stringResource(R.string.delete_record))
                            }
                        }
                    }
                }
            }
        }
    }
    selectedBatch?.let { batch ->
        AlertDialog(
            onDismissRequest = { selectedBatch = null },
            title = { Text(batch.backupId) },
            text = {
                LazyColumn(Modifier.heightIn(max = 420.dp)) {
                    items(parts, key = { it.partId }) { part ->
                        Row(
                            Modifier.fillMaxWidth().padding(vertical = 6.dp),
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Text(
                                "${part.partNumber}/${batch.partCount} · ${part.status.name}",
                                Modifier.weight(1f)
                            )
                            if (part.status != EmailBackupPartStatus.CONFIRMED_SENT) {
                                TextButton(onClick = {
                                    scope.launch {
                                        try {
                                            val email = vm.createIntent(part.partId)
                                            launcher.launch(email.intent)
                                            vm.markOpened(part.partId)
                                        } catch (exception: Exception) {
                                            error = exception.message ?: "open_email_failed"
                                        }
                                    }
                                }) { Text(stringResource(R.string.continue_sending)) }
                            }
                        }
                    }
                }
            },
            confirmButton = {
                TextButton(onClick = { selectedBatch = null }) {
                    Text(stringResource(R.string.confirm))
                }
            }
        )
    }
    confirmSent?.let { batch ->
        AlertDialog(
            onDismissRequest = { confirmSent = null },
            title = { Text(stringResource(R.string.mark_sent)) },
            text = { Text(stringResource(R.string.manual_sent_warning)) },
            confirmButton = {
                TextButton(onClick = {
                    vm.markBatchSent(batch.backupId)
                    confirmSent = null
                }) { Text(stringResource(R.string.confirm)) }
            },
            dismissButton = {
                TextButton(onClick = { confirmSent = null }) {
                    Text(stringResource(R.string.cancel))
                }
            }
        )
    }
    deleteBatch?.let { batch ->
        AlertDialog(
            onDismissRequest = { deleteBatch = null },
            title = { Text(stringResource(R.string.delete_record)) },
            text = {
                Text(stringResource(
                    if (batch.status == EmailBackupBatchStatus.CONFIRMED_SENT) {
                        R.string.delete_confirmed_record_warning
                    } else {
                        R.string.delete_record_warning
                    }
                ))
            },
            confirmButton = {
                TextButton(onClick = {
                    vm.deleteRecord(batch.backupId)
                    deleteBatch = null
                }) { Text(stringResource(R.string.confirm)) }
            },
            dismissButton = {
                TextButton(onClick = { deleteBatch = null }) {
                    Text(stringResource(R.string.cancel))
                }
            }
        )
    }
    if (error != null) {
        AlertDialog(
            onDismissRequest = { error = null },
            title = { Text(stringResource(R.string.backup_error_title)) },
            text = { Text(backupErrorText(error!!)) },
            confirmButton = {
                TextButton(onClick = { error = null }) {
                    Text(stringResource(R.string.confirm))
                }
            }
        )
    }
    if (awaitingPart != null) {
        SendConfirmationDialog(
            part = awaitingPart!!,
            onSent = { vm.confirmPartSent(awaitingPart!!.partId) },
            onNotSent = { vm.reportPartNotSent(awaitingPart!!.partId) },
            onReopen = {
                scope.launch {
                    try {
                        val email = vm.createIntent(awaitingPart!!.partId)
                        launcher.launch(email.intent)
                        vm.markOpened(awaitingPart!!.partId)
                    } catch (exception: Exception) {
                        error = exception.message ?: "open_email_failed"
                    }
                }
            },
            onEnd = { vm.setAwaitingPart(null) }
        )
    }
}

@Composable
private fun RangeChip(
    value: EmailBackupRange,
    current: EmailBackupRange,
    onClick: (EmailBackupRange) -> Unit
) {
    FilterChip(
        selected = value == current,
        onClick = { onClick(value) },
        label = { Text(stringResource(rangeString(value))) }
    )
}

@Composable
private fun SectionTitle(value: String) {
    Text(
        value,
        fontWeight = FontWeight.Bold,
        modifier = Modifier.padding(top = 16.dp, bottom = 6.dp)
    )
}

@Composable
private fun CheckLine(title: String, checked: Boolean, onClick: () -> Unit) {
    Row(
        Modifier.fillMaxWidth().clickable(onClick = onClick).padding(vertical = 3.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        Checkbox(checked = checked, onCheckedChange = { onClick() })
        Text(title)
    }
}

@Composable
private fun SwitchLine(title: String, checked: Boolean, onChange: (Boolean) -> Unit) {
    Row(
        Modifier.fillMaxWidth().clickable { onChange(!checked) }.padding(vertical = 4.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        Text(title, Modifier.weight(1f))
        Switch(checked = checked, onCheckedChange = onChange)
    }
}

@Composable
private fun InfoLine(title: String, detail: String) {
    Row(Modifier.fillMaxWidth().padding(vertical = 3.dp)) {
        Text(title, Modifier.weight(1f), fontWeight = FontWeight.SemiBold)
        Text(detail)
    }
}

@Composable
private fun backupStatusText(status: EmailBackupBatchStatus): String = stringResource(when (status) {
    EmailBackupBatchStatus.GENERATED -> R.string.status_generated
    EmailBackupBatchStatus.GMAIL_OPENED -> R.string.status_gmail_opened
    EmailBackupBatchStatus.PARTIALLY_CONFIRMED -> R.string.status_partial
    EmailBackupBatchStatus.CONFIRMED_SENT -> R.string.status_confirmed
    EmailBackupBatchStatus.USER_REPORTED_NOT_SENT -> R.string.status_not_sent
    EmailBackupBatchStatus.FAILED -> R.string.status_failed
})

@Composable
private fun backupErrorText(code: String): String = stringResource(when (code) {
    "invalid_recipient" -> R.string.error_invalid_recipient
    "sms_query_failed" -> R.string.error_sms_query
    "sms_permission_missing" -> R.string.error_sms_permission
    "no_matching_messages" -> R.string.error_no_matching_messages
    "attachment_write_failed" -> R.string.error_attachment_write
    "export_files_missing" -> R.string.error_export_missing
    "no_email_app" -> R.string.error_no_email_app
    else -> R.string.error_backup_generic
})

private fun rangeString(value: EmailBackupRange): Int = when (value) {
    EmailBackupRange.UNBACKED -> R.string.range_unbacked
    EmailBackupRange.LAST_7_DAYS -> R.string.range_7_days
    EmailBackupRange.LAST_30_DAYS -> R.string.range_30_days
    EmailBackupRange.THIS_MONTH -> R.string.range_this_month
    EmailBackupRange.CUSTOM -> R.string.range_custom
}

@StringRes
private fun categoryStringRes(category: SmsCategory): Int = when (category) {
    SmsCategory.OTP -> R.string.category_otp
    SmsCategory.ADVERTISEMENT -> R.string.category_ad
    SmsCategory.DELIVERY -> R.string.category_delivery
    SmsCategory.PERSON -> R.string.category_person
    SmsCategory.NOTICE -> R.string.category_notice
    SmsCategory.UNKNOWN -> R.string.category_other
}

private fun formatRange(start: Long, end: Long): String {
    val formatter = DateFormat.getDateInstance(DateFormat.MEDIUM)
    return "${formatter.format(Date(start))} – ${formatter.format(Date(end))}"
}
